// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CssVariablesTable: typeof import('./src/components/tables/CssVariablesTable.vue')['default']
    DesignSystemDefaultCode: typeof import('./src/components/sections/index/code/design-system-default-code.md')['default']
    DesignSystemLoginCard: typeof import('./src/components/sections/index/components/DesignSystemLoginCard.vue')['default']
    DesignSystemPostCard: typeof import('./src/components/sections/index/components/DesignSystemPostCard.vue')['default']
    DesignSystemPricingCard: typeof import('./src/components/sections/index/components/DesignSystemPricingCard.vue')['default']
    DesignSystemProfileCard: typeof import('./src/components/sections/index/components/DesignSystemProfileCard.vue')['default']
    DesignSystemTasksCard: typeof import('./src/components/sections/index/components/DesignSystemTasksCard.vue')['default']
    Docsearch: typeof import('./src/components/forms/Docsearch.vue')['default']
    EventsTable: typeof import('./src/components/tables/EventsTable.vue')['default']
    Example: typeof import('./src/components/common/Example.vue')['default']
    FeatureBox: typeof import('./src/components/cards/FeatureBox.vue')['default']
    Footer: typeof import('./src/components/navigation/Footer.vue')['default']
    IconFaBrandsDiscord: typeof import('~icons/fa-brands/discord')['default']
    IconFaBrandsGithub: typeof import('~icons/fa-brands/github')['default']
    IconFaBrandsTwitter: typeof import('~icons/fa-brands/twitter')['default']
    IconFaRegularClone: typeof import('~icons/fa-regular/clone')['default']
    IconFaSolidBook: typeof import('~icons/fa-solid/book')['default']
    IconFaSolidCheckCircle: typeof import('~icons/fa-solid/check-circle')['default']
    IconFaSolidCode: typeof import('~icons/fa-solid/code')['default']
    IconFaSolidComments: typeof import('~icons/fa-solid/comments')['default']
    IconFaSolidGlob: typeof import('~icons/fa-solid/glob')['default']
    IconFaSolidGlobe: typeof import('~icons/fa-solid/globe')['default']
    IconFaSolidHeart: typeof import('~icons/fa-solid/heart')['default']
    IconFaSolidMoon: typeof import('~icons/fa-solid/moon')['default']
    IconFaSolidSun: typeof import('~icons/fa-solid/sun')['default']
    IndexDesignSystemSection: typeof import('./src/components/sections/index/IndexDesignSystemSection.vue')['default']
    IndexExampleEmbedSection: typeof import('./src/components/sections/index/IndexExampleEmbedSection.vue')['default']
    IndexHeaderSection: typeof import('./src/components/sections/index/IndexHeaderSection.vue')['default']
    IndexOsAwardsSection: typeof import('./src/components/sections/index/IndexOsAwardsSection.vue')['default']
    IndexSponsorsSection: typeof import('./src/components/sections/index/IndexSponsorsSection.vue')['default']
    IndexUiUxDxSection: typeof import('./src/components/sections/index/IndexUiUxDxSection.vue')['default']
    Navbar: typeof import('./src/components/navigation/Navbar.vue')['default']
    OsAwards: typeof import('./src/components/cards/OsAwards.vue')['default']
    PageNavigation: typeof import('./src/components/navigation/PageNavigation.vue')['default']
    PropsTable: typeof import('./src/components/tables/PropsTable.vue')['default']
    SectionHeader: typeof import('./src/components/common/SectionHeader.vue')['default']
    Sidebar: typeof import('./src/components/navigation/Sidebar.vue')['default']
    SlotsTable: typeof import('./src/components/tables/SlotsTable.vue')['default']
  }
}

export { }
