// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DesignSystemDefaultCode: typeof import('./src/components/sections/index/code/design-system-default-code.md')['default']
    DesignSystemLoginCard: typeof import('./src/components/sections/index/components/DesignSystemLoginCard.vue')['default']
    DesignSystemPostCard: typeof import('./src/components/sections/index/components/DesignSystemPostCard.vue')['default']
    DesignSystemPricingCard: typeof import('./src/components/sections/index/components/DesignSystemPricingCard.vue')['default']
    DesignSystemProfileCard: typeof import('./src/components/sections/index/components/DesignSystemProfileCard.vue')['default']
    DesignSystemTasksCard: typeof import('./src/components/sections/index/components/DesignSystemTasksCard.vue')['default']
    Example: typeof import('./src/components/common/Example.vue')['default']
    FeatureBox: typeof import('./src/components/cards/FeatureBox.vue')['default']
    IndexDesignSystemSection: typeof import('./src/components/sections/index/IndexDesignSystemSection.vue')['default']
    IndexExampleEmbedSection: typeof import('./src/components/sections/index/IndexExampleEmbedSection.vue')['default']
    IndexHeaderSection: typeof import('./src/components/sections/index/IndexHeaderSection.vue')['default']
    IndexOsAwardsSection: typeof import('./src/components/sections/index/IndexOsAwardsSection.vue')['default']
    IndexUiUxDxSection: typeof import('./src/components/sections/index/IndexUiUxDxSection.vue')['default']
    Navbar: typeof import('./src/components/navigation/Navbar.vue')['default']
    OsAwards: typeof import('./src/components/cards/OsAwards.vue')['default']
    SectionHeader: typeof import('./src/components/common/SectionHeader.vue')['default']
    Sidebar: typeof import('./src/components/navigation/Sidebar.vue')['default']
  }
}

export { }
