// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CssVariablesTable: typeof import('./components/tables/CssVariablesTable.vue')['default']
    DesignSystemDefaultCode: typeof import('./components/sections/index/code/design-system-default-code.md')['default']
    DesignSystemLoginCard: typeof import('./components/sections/index/components/DesignSystemLoginCard.vue')['default']
    DesignSystemPostCard: typeof import('./components/sections/index/components/DesignSystemPostCard.vue')['default']
    DesignSystemPricingCard: typeof import('./components/sections/index/components/DesignSystemPricingCard.vue')['default']
    DesignSystemProfileCard: typeof import('./components/sections/index/components/DesignSystemProfileCard.vue')['default']
    DesignSystemTasksCard: typeof import('./components/sections/index/components/DesignSystemTasksCard.vue')['default']
    Docsearch: typeof import('./components/forms/Docsearch.vue')['default']
    EventsTable: typeof import('./components/tables/EventsTable.vue')['default']
    Example: typeof import('./components/common/Example.vue')['default']
    FeatureBox: typeof import('./components/cards/FeatureBox.vue')['default']
    Footer: typeof import('./components/navigation/Footer.vue')['default']
    IndexDesignSystemSection: typeof import('./components/sections/index/IndexDesignSystemSection.vue')['default']
    IndexExampleEmbedSection: typeof import('./components/sections/index/IndexExampleEmbedSection.vue')['default']
    IndexHeaderSection: typeof import('./components/sections/index/IndexHeaderSection.vue')['default']
    IndexOsAwardsSection: typeof import('./components/sections/index/IndexOsAwardsSection.vue')['default']
    IndexSponsorsSection: typeof import('./components/sections/index/IndexSponsorsSection.vue')['default']
    IndexUiUxDxSection: typeof import('./components/sections/index/IndexUiUxDxSection.vue')['default']
    Navbar: typeof import('./components/navigation/Navbar.vue')['default']
    OsAwards: typeof import('./components/cards/OsAwards.vue')['default']
    PageNavigation: typeof import('./components/navigation/PageNavigation.vue')['default']
    PropsTable: typeof import('./components/tables/PropsTable.vue')['default']
    SectionHeader: typeof import('./components/common/SectionHeader.vue')['default']
    Sidebar: typeof import('./components/navigation/Sidebar.vue')['default']
    SlotsTable: typeof import('./components/tables/SlotsTable.vue')['default']
  }
}

export { }
